### ISSUE TITLE
Haggle

### ISSUE THREAD

**Issue by ghost** [daniellok/neopets-autobuyer#3]

**Comment by daniellok** [comment]
@Rynac "Missed haggle" means that the autobuyer was able to offer on the item, but someone else got it first. "No haggle" means that someone got the item before the autobuyer could make an offer. In both cases, the item is "Sold out"! 

Additionally, there is a very low probability that the method I use for solving the CAPTCHA (i.e. clicking on the neopet) fails, but in the vast majority of cases, items are missed because of lag/unlucky refreshes rather than that.

**Comment by Rynac** [comment]
Tks! :)
